// Generated by Wrangler by running `wrangler types`

interface Env {
	INTERNAL_BASIC_AUTH_USERNAME: string;
	INTERNAL_BASIC_AUTH_PASSWORD: string;
	CLOUDFLARE_API_KEY: string;
	CLOUDFLARE_AUTH_EMAIL: string;
	CLOUDFLARE_ZONE_ID: string;
	CLOUDFLARE_DNS_RECORD_ID: string;
}
