#:schema node_modules/wrangler/config-schema.json
name = "ddns-worker"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]
node_compat = true

[observability]
enabled = true
